package io.matthewnelson.sampleapp.util

object PrefKeys {
    // Notification
    const val NOTIFICATION_VISIBILITY = "NOTIFICATION_VISIBILITY"
    const val NOTIFICATION_COLOR_RESOURCE = "NOTIFICATION_COLOR_RESOURCE"
    const val NOTIFICATION_ENABLE_RESTART = "NOTIFICATION_ENABLE_RESTART"
    const val NOTIFICATION_ENABLE_STOP = "NOTIFICATION_ENABLE_STOP"
    const val NOTIFICATION_SHOW = "NOTIFICATION_SHOW"

    // BackgroundManager Policy
    const val BACKGROUND_MANAGER_POLICY = "BACKGROUND_MANAGER_POLICY"
    const val BACKGROUND_MANAGER_POLICY_RESPECT = "BACKGROUND_MANAGER_POLICY_RESPECT"
    const val BACKGROUND_MANAGER_POLICY_FOREGROUND = "BACKGROUND_MANAGER_POLICY_FOREGROUND"
    const val BACKGROUND_MANAGER_EXECUTE_DELAY = "BACKGROUND_MANAGER_EXECUTE_DELAY"
    const val BACKGROUND_MANAGER_KILL_APP = "BACKGROUND_MANAGER_KILL_APP"

    // Controller
    const val CONTROLLER_BUILD_CONFIG_DEBUG = "CONTROLLER_BUILD_CONFIG_DEBUG"
    const val CONTROLLER_RESTART_DELAY = "CONTROLLER_RESTART_DELAY"
    const val CONTROLLER_STOP_DELAY = "CONTROLLER_STOP_DELAY"
    const val CONTROLLER_DISABLE_STOP_SERVICE_TASK_REMOVED = "CONTROLLER_DISABLE_STOP_SERVICE_TASK_REMOVED"
}